# Generated by Django 5.2.4 on 2025-07-30 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('city', models.CharField(max_length=100)),
                ('codeno', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Studentdata',
                'db_table': 'Student',
            },
        ),
    ]
