# Generated by Django 5.2.4 on 2025-08-15 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcloud', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='video',
            field=models.FileField(default='videos/default.mp4', upload_to='video/'),
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='image',
            field=models.ImageField(upload_to='image/'),
        ),
    ]
