# Generated by Django 5.2.4 on 2025-08-15 11:59

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcloud', '0002_student_video_alter_student_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='image',
            field=models.ImageField(storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='image/'),
        ),
        migrations.AlterField(
            model_name='student',
            name='video',
            field=models.FileField(default='videos/default.mp4', storage=cloudinary_storage.storage.VideoMediaCloudinaryStorage(), upload_to='video/'),
        ),
    ]
