# Generated by Django 5.2.5 on 2025-08-29 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumini',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('empid', models.CharField(max_length=150)),
                ('mobile', models.IntegerField()),
                ('designation', models.CharField()),
                ('salary', models.CharField()),
                ('city', models.CharField()),
            ],
            options={
                'db_table': 'Alumini',
            },
        ),
    ]
