# Generated by Django 5.2.5 on 2025-08-29 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumini',
            name='mobile',
            field=models.CharField(),
        ),
    ]
