# Generated by Django 5.2.5 on 2025-08-06 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apppdf', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='dob',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='city',
            field=models.CharField(max_length=50),
        ),
    ]
